version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
        - '3306:3306'